---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks
- Pedreiro-Digital-Studio:
    - Repositories:
        - icon: github-light.png
          href: https://github.com/Pedreiro-Digital-Studio-Ltda/repositories
