---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Utilities:
    - Gmail:
        icon: gmail.png
        href: https://gmail.com
        description: Gmail
    - Translate:
        icon: google-translate.png
        href: https://translate.google.com.br/?hl=pt-BR
        description: Google Translate
    - Youtube:
        icon: youtube.png
        href: https://youtube.com
        description: Youtube
    - ChatGPT:
        icon: chatgpt.png
        href: https://chat.openai.com/
        description: Chat Open Ai

- Favorites:
    - Notion:
        icon: notion-light.png
        href: https://www.notion.so/faoliveirajr/
        description: Notion with every annotations
    - Cloud MongoDb Access:
        icon: mongodb.png
        href: https://account.mongodb.com/account/login
        description: MongoDb Atlas Access (Login with sso google)
    - Mongo PlayGround:
        icon: mongodb.png
        href: https://mongoplayground.net/
        description: MongoDb PlayGround
    - Simples Nacional (BR PJ):
        icon: cloudpanel.svg
        href: https://www8.receita.fazenda.gov.br/SimplesNacional/Servicos/Grupo.aspx?grp=t&area=1
        description: Site para validar informações da PJ 
    - ISS Fortaleza (BR PJ):
        icon: cloudpanel.svg
        href: https://iss.fortaleza.ce.gov.br/grpfor/login.seam?cid=137794
        description: Site para emissão/gerenciamento de notas fiscais
    - Agilize Contabilidade:
        icon: cloudpanel.svg
        href: https://app.agilize.com.br/#/
        description: Contabilidade Online [47584961000154]

- Daily Job:
    - Jira:
        icon: jira.png
        href: https://jira.linx.com.br/secure/RapidBoard.jspa?projectKey=OMNI&rapidView=1198
        description: OMS - Jira Sprint
    - Outlook:
        icon: microsoft-todo.png
        href: https://outlook.office.com/mail/
        description: Personal Account
    - Microsoft:
        icon: microsoft.png
        href: https://myaccount.microsoft.com/
        description: Personal Account
    - Circle-CI:
        icon: /images/Circleci-icon-logo.png
        href: https://app.circleci.com/pipelines/github/chaordic/oms-cockpit
        description: Process Build CI/CD
    - Daywork:
        icon: /images/daywork.png
        href: https://daywork.com.br/
        description: Other Jobs
    - Daywork:
        icon: workadventure.png
        href: https://play.workadventu.re/@/itarget-tecnologia/itarget/startup
        description: iTarget Work Adventure

- Linx Url Help:
    - COCKPIT [PRD]:
        icon: /images/linx.jpg
        href: https://oms.chaordic.com.br/deliveries/all
        description: Aplicação Cockpit - Produção
    - COCKPIT [HLG]:
        icon: /images/linx.jpg
        href: https://oms-homolog.chaordic.com.br/deliveries/all
        description: Aplicação Cockpit - Homologação
    - REMOTE-CONFIG [PRD]:
        icon: /images/linx.jpg
        href: http://production-remote-config.omniplat.internal/login
        description: Aplicação Remote Config - Produção
    - REMOTE-CONFIG [HLG]:
        icon: /images/linx.jpg
        href: http://homolog-remote-config.omniplat.internal/login
        description: Aplicação Remote Config - Homologação
    - NIFI [PRD]:
        icon: /images/linx.jpg
        href: https://production-nifi-oms-sales.omniplat.io/nifi/login
        description: Aplicação NIFI Sales - Produção
    - NIFI [HLG]:
        icon: /images/linx.jpg
        href: https://homolog-nifi-oms-logistics.omniplat.io/nifi/login
        description: Aplicação NIFI Sales - Homologação
    - SHARE:
        icon: /images/linx.jpg
        href: https://share.linx.com.br/#all-updates
        description: Linx Share - Documentação

- Application Monitoring:
    - Sig.recsodine:
        icon: radarr.png
        href: https://sig.recsodine.com.br/
        siteMonitor: https://sig.recsodine.com.br/
    - Eco.silence:
        icon: radarr.png
        href: https://gestao.ecosilence.com.br/
        siteMonitor: https://gestao.ecosilence.com.br/
    - Educa:
        icon: radarr.png
        href: https://gestao.educandariotiajade.com.br/
        siteMonitor: https://gestao.educandariotiajade.com.br/

# - SpeedTest:
#     - SpeedTest:
#         icon: speedtest-tracker.png
#         href: http://189.25.103.120
#         description: SpeedTest
#         widget:
#             type: speedtest
#             url: http://189.25.103.120