---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- AREA PJ:
    - Simples Nacional (BR PJ):
        icon: cloudpanel.svg
        href: https://www8.receita.fazenda.gov.br/SimplesNacional/Servicos/Grupo.aspx?grp=t&area=1
        description: Site para validar informações da PJ 
    - ISS Fortaleza (BR PJ):
        icon: cloudpanel.svg
        href: https://iss.fortaleza.ce.gov.br/grpfor/login.seam?cid=137794
        description: Site para emissão/gerenciamento de notas fiscais
    - Agilize Contabilidade:
        icon: cloudpanel.svg
        href: https://app.agilize.com.br/#/
        description: Contabilidade Online [47584961000154]

- Application Monitoring:
    - Sig.recsodine:
        icon: radarr.png
        href: https://sig.recsodine.com.br/
        siteMonitor: https://sig.recsodine.com.br/
    - API.verdesec:
        icon: radarr.png
        href: https://api.verdesec.com.br/api
        siteMonitor: https://api.verdesec.com.br/api
